
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GREATERTHAN = 31;
  public static final int DIVIDE = 8;
  public static final int CBRACE = 26;
  public static final int INCREMENT = 27;
  public static final int CHAR = 45;
  public static final int STR = 49;
  public static final int SEMI = 9;
  public static final int INT = 42;
  public static final int FLS = 41;
  public static final int PRINTLN = 17;
  public static final int MINUS = 7;
  public static final int DECREMENT = 28;
  public static final int OBRACE = 25;
  public static final int OBRACKET = 23;
  public static final int OROR = 19;
  public static final int LEQUALTO = 32;
  public static final int INTLIT = 50;
  public static final int CBRACKET = 24;
  public static final int LESSTHAN = 30;
  public static final int BOOL = 44;
  public static final int COMMA = 38;
  public static final int CLASS = 2;
  public static final int FI = 15;
  public static final int ANDAND = 20;
  public static final int PLUS = 6;
  public static final int IF = 14;
  public static final int ID = 48;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int error = 1;
  public static final int EQEQ = 29;
  public static final int TRU = 40;
  public static final int VOID = 39;
  public static final int OPARENTH = 21;
  public static final int FLOATLIT = 46;
  public static final int EQ = 10;
  public static final int CPARENTH = 22;
  public static final int TIMES = 5;
  public static final int CHARLIT = 47;
  public static final int COLON = 37;
  public static final int ELSE = 13;
  public static final int READ = 3;
  public static final int FINAL = 12;
  public static final int WHILE = 16;
  public static final int FLOAT = 43;
  public static final int QUESTION = 36;
  public static final int SIMILAR = 35;
  public static final int GEQUALTO = 33;
  public static final int VAR = 11;
  public static final int LESSGREAT = 34;
  public static final int PRINT = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "READ",
  "PRINT",
  "TIMES",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "SEMI",
  "EQ",
  "VAR",
  "FINAL",
  "ELSE",
  "IF",
  "FI",
  "WHILE",
  "PRINTLN",
  "RETURN",
  "OROR",
  "ANDAND",
  "OPARENTH",
  "CPARENTH",
  "OBRACKET",
  "CBRACKET",
  "OBRACE",
  "CBRACE",
  "INCREMENT",
  "DECREMENT",
  "EQEQ",
  "LESSTHAN",
  "GREATERTHAN",
  "LEQUALTO",
  "GEQUALTO",
  "LESSGREAT",
  "SIMILAR",
  "QUESTION",
  "COLON",
  "COMMA",
  "VOID",
  "TRU",
  "FLS",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "FLOATLIT",
  "CHARLIT",
  "ID",
  "STR",
  "INTLIT"
  };
}

